apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orders-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-orders
  template:
    metadata:
      labels:
        app: ms-orders
    spec:
      containers:
        - name: ms-orders
          image: fc61009.ddns.net:3389/ms_orders_api:latest
          ports:
            - containerPort: 8080
