apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orders-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-orders
  template:
    metadata:
      labels:
        app: ms-orders
    spec:
      containers:
        - name: ms-orders
          image: northamerica-northeast1-docker.pkg.dev/coral-inverter-421114/fcul-project/ms_orders_api:latest
          ports:
            - containerPort: 8080
