apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-orders-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-orders-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50
  updatePolicy:
    updateBudget:
      maxSurge: 25%
      maxUnavailable: 25%
    autoScalingPolicy:
      cooldownPeriod: 60s
      stabilizationWindow: 300s
