apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-customers-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-customers
  template:
    metadata:
      labels:
        app: ms-customers
    spec:
      containers:
        - name: ms-customers
          image: fc61009.ddns.net:3389/ms_customers_api:latest
          ports:
            - containerPort: 8080
