apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-customers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-customers-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
