apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-products-deployment
spec:
  selector:
    matchLabels:
      app: mysql-products
  template:
    metadata:
      labels:
        app: mysql-products
    spec:
      containers:
        - name: mysql-products
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: "olist_products"
            - name: MYSQL_USER
              value: "olist_myuser"
            - name: MYSQL_PASSWORD
              value: "olist_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
            - name: MYSQL_TCP_PORT
              value: "3308"
          ports:
            - containerPort: 3308
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-ms-products-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-ms-products-storage
          persistentVolumeClaim:
            claimName: mysql-products-pd-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-products
  template:
    metadata:
      labels:
        app: ms-products
    spec:
      containers:
        - name: ms-products
          image: northamerica-northeast1-docker.pkg.dev/coral-inverter-421114/fcul-project/ms_products_api:latest
          env:
            - name: MYSQL_HOST
              value: "mysql_products"
            - name: MYSQL_DATABASE
              value: "olist_products"
            - name: MYSQL_USER
              value: "olist_myuser"
            - name: MYSQL_PASSWORD
              value: "olist_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
            - name: MYSQL_TCP_PORT
              value: "3308"
          ports:
            - containerPort: 5000
