apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-products-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-products-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
