apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  rules:
    - host: domain-or-ip
      http:
        paths:
          - pathType: Prefix
            path: "/orders"
            backend:
              service:
                name: ms-orders-service
                port:
                  number: 8080
          - pathType: Prefix
            path: "/customers"
            backend:
              service:
                name: ms-customers-service
                port:
                  number: 8080
          - pathType: Prefix
            path: "/products"
            backend:
              service:
                name: ms-products-service
                port:
                  number: 8080
