apiVersion: v1
kind: Service
metadata:
  name: ms-orders-service
spec:
  selector:
    app: ms-orders
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ms-customers-service
spec:
  selector:
    app: ms-customers
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ms-products-service
spec:
  selector:
    app: ms-products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-products
spec:
  selector:
    app: mysql-products
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3308

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-orders
spec:
  selector:
    app: mysql-orders
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3309
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-customers
spec:
  selector:
    app: mysql-customers
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307
