apiVersion: v1
kind: Service
metadata:
  name: ms-orders-service
spec:
  selector:
    app: ms-orders
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: ms-customers-service
spec:
  selector:
    app: ms-customers
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: ms-products-service
spec:
  selector:
    app: ms-products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
