version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
     - .env
    ports:
      - '3308:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  api:
    build: .
    ports:
      - '5002:5002'
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql_data:
    driver: local
