# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"\x17\n\x15GetAllProductsRequest\"\x90\x02\n\x14\x43reateProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1d\n\x15product_category_name\x18\x02 \x01(\t\x12\x1b\n\x13product_name_length\x18\x03 \x01(\x05\x12\"\n\x1aproduct_description_length\x18\x04 \x01(\x05\x12\x1a\n\x12product_photos_qty\x18\x05 \x01(\x05\x12\x18\n\x10product_weight_g\x18\x06 \x01(\x05\x12\x19\n\x11product_length_cm\x18\x07 \x01(\x05\x12\x19\n\x11product_height_cm\x18\x08 \x01(\x05\x12\x18\n\x10product_width_cm\x18\t \x01(\x05\"\x90\x02\n\x14UpdateProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1d\n\x15product_category_name\x18\x02 \x01(\t\x12\x1b\n\x13product_name_length\x18\x03 \x01(\x05\x12\"\n\x1aproduct_description_length\x18\x04 \x01(\x05\x12\x1a\n\x12product_photos_qty\x18\x05 \x01(\x05\x12\x18\n\x10product_weight_g\x18\x06 \x01(\x05\x12\x19\n\x11product_length_cm\x18\x07 \x01(\x05\x12\x19\n\x11product_height_cm\x18\x08 \x01(\x05\x12\x18\n\x10product_width_cm\x18\t \x01(\x05\"\x83\x02\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1d\n\x15product_category_name\x18\x02 \x01(\t\x12\x1b\n\x13product_name_length\x18\x03 \x01(\x05\x12\"\n\x1aproduct_description_length\x18\x04 \x01(\x05\x12\x1a\n\x12product_photos_qty\x18\x05 \x01(\x05\x12\x18\n\x10product_weight_g\x18\x06 \x01(\x05\x12\x19\n\x11product_length_cm\x18\x07 \x01(\x05\x12\x19\n\x11product_height_cm\x18\x08 \x01(\x05\x12\x18\n\x10product_width_cm\x18\t \x01(\x05\"2\n\x0bProductList\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product2\xe8\x01\n\x0eProductService\x12J\n\x0eGetAllProducts\x12\x1f.products.GetAllProductsRequest\x1a\x15.products.ProductList\"\x00\x12\x44\n\rCreateProduct\x12\x1e.products.CreateProductRequest\x1a\x11.products.Product\"\x00\x12\x44\n\rUpdateProduct\x12\x1e.products.UpdateProductRequest\x1a\x11.products.Product\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETALLPRODUCTSREQUEST']._serialized_start=28
  _globals['_GETALLPRODUCTSREQUEST']._serialized_end=51
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=54
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=326
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=329
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=601
  _globals['_PRODUCT']._serialized_start=604
  _globals['_PRODUCT']._serialized_end=863
  _globals['_PRODUCTLIST']._serialized_start=865
  _globals['_PRODUCTLIST']._serialized_end=915
  _globals['_PRODUCTSERVICE']._serialized_start=918
  _globals['_PRODUCTSERVICE']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
