# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customers_pb2 as customers__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllCustomers = channel.unary_unary(
                '/customer.CustomerService/GetAllCustomers',
                request_serializer=customers__pb2.CustomerRequest.SerializeToString,
                response_deserializer=customers__pb2.CustomerList.FromString,
                )
        self.CreateCustomer = channel.unary_unary(
                '/customer.CustomerService/CreateCustomer',
                request_serializer=customers__pb2.Customer.SerializeToString,
                response_deserializer=customers__pb2.Customer.FromString,
                )
        self.DeleteAllCustomers = channel.unary_unary(
                '/customer.CustomerService/DeleteAllCustomers',
                request_serializer=customers__pb2.Empty.SerializeToString,
                response_deserializer=customers__pb2.Empty.FromString,
                )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllCustomers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllCustomers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllCustomers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCustomers,
                    request_deserializer=customers__pb2.CustomerRequest.FromString,
                    response_serializer=customers__pb2.CustomerList.SerializeToString,
            ),
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=customers__pb2.Customer.FromString,
                    response_serializer=customers__pb2.Customer.SerializeToString,
            ),
            'DeleteAllCustomers': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllCustomers,
                    request_deserializer=customers__pb2.Empty.FromString,
                    response_serializer=customers__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customer.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllCustomers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/GetAllCustomers',
            customers__pb2.CustomerRequest.SerializeToString,
            customers__pb2.CustomerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/CreateCustomer',
            customers__pb2.Customer.SerializeToString,
            customers__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAllCustomers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer.CustomerService/DeleteAllCustomers',
            customers__pb2.Empty.SerializeToString,
            customers__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
