# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customers.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ustomers.proto\x12\x08\x63ustomer\"\x8c\x01\n\x08\x43ustomer\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63ustomer_unique_id\x18\x02 \x01(\t\x12 \n\x18\x63ustomer_zip_code_prefix\x18\x03 \x01(\t\x12\x15\n\rcustomer_city\x18\x04 \x01(\t\x12\x16\n\x0e\x63ustomer_state\x18\x05 \x01(\t\"\x11\n\x0f\x43ustomerRequest\"5\n\x0c\x43ustomerList\x12%\n\tcustomers\x18\x01 \x03(\x0b\x32\x12.customer.Customer\"\x07\n\x05\x45mpty2\xcf\x01\n\x0f\x43ustomerService\x12\x46\n\x0fGetAllCustomers\x12\x19.customer.CustomerRequest\x1a\x16.customer.CustomerList\"\x00\x12:\n\x0e\x43reateCustomer\x12\x12.customer.Customer\x1a\x12.customer.Customer\"\x00\x12\x38\n\x12\x44\x65leteAllCustomers\x12\x0f.customer.Empty\x1a\x0f.customer.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOMER']._serialized_start=30
  _globals['_CUSTOMER']._serialized_end=170
  _globals['_CUSTOMERREQUEST']._serialized_start=172
  _globals['_CUSTOMERREQUEST']._serialized_end=189
  _globals['_CUSTOMERLIST']._serialized_start=191
  _globals['_CUSTOMERLIST']._serialized_end=244
  _globals['_EMPTY']._serialized_start=246
  _globals['_EMPTY']._serialized_end=253
  _globals['_CUSTOMERSERVICE']._serialized_start=256
  _globals['_CUSTOMERSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
