# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customers.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ustomers.proto\x12\x08\x63ustomer\"&\n\x0f\x43ustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"\x1f\n\x10\x43ustomerResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2X\n\x0f\x43ustomerService\x12\x45\n\nIsCustomer\x12\x19.customer.CustomerRequest\x1a\x1a.customer.CustomerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERREQUEST']._serialized_start=29
  _globals['_CUSTOMERREQUEST']._serialized_end=67
  _globals['_CUSTOMERRESPONSE']._serialized_start=69
  _globals['_CUSTOMERRESPONSE']._serialized_end=100
  _globals['_CUSTOMERSERVICE']._serialized_start=102
  _globals['_CUSTOMERSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
