# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orders_pb2 as orders__pb2


class OrderServiceStub(object):
    """Definição do serviço gRPC para orders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomerInfo = channel.unary_unary(
                '/OrderService/GetCustomerInfo',
                request_serializer=orders__pb2.CustomerRequest.SerializeToString,
                response_deserializer=orders__pb2.CustomerResponse.FromString,
                )
        self.GetProductInfo = channel.unary_unary(
                '/OrderService/GetProductInfo',
                request_serializer=orders__pb2.ProductRequest.SerializeToString,
                response_deserializer=orders__pb2.ProductResponse.FromString,
                )


class OrderServiceServicer(object):
    """Definição do serviço gRPC para orders
    """

    def GetCustomerInfo(self, request, context):
        """Método para obter informações de um cliente pelo ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductInfo(self, request, context):
        """Método para obter informações de um produto pelo ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerInfo,
                    request_deserializer=orders__pb2.CustomerRequest.FromString,
                    response_serializer=orders__pb2.CustomerResponse.SerializeToString,
            ),
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=orders__pb2.ProductRequest.FromString,
                    response_serializer=orders__pb2.ProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Definição do serviço gRPC para orders
    """

    @staticmethod
    def GetCustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderService/GetCustomerInfo',
            orders__pb2.CustomerRequest.SerializeToString,
            orders__pb2.CustomerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderService/GetProductInfo',
            orders__pb2.ProductRequest.SerializeToString,
            orders__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
