# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x0f\x43ustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\">\n\x10\x43ustomerResponse\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\";\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t2{\n\x0cOrderService\x12\x36\n\x0fGetCustomerInfo\x12\x10.CustomerRequest\x1a\x11.CustomerResponse\x12\x33\n\x0eGetProductInfo\x12\x0f.ProductRequest\x1a\x10.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOMERREQUEST']._serialized_start=45
  _globals['_CUSTOMERREQUEST']._serialized_end=83
  _globals['_CUSTOMERRESPONSE']._serialized_start=85
  _globals['_CUSTOMERRESPONSE']._serialized_end=147
  _globals['_PRODUCTREQUEST']._serialized_start=149
  _globals['_PRODUCTREQUEST']._serialized_end=185
  _globals['_PRODUCTRESPONSE']._serialized_start=187
  _globals['_PRODUCTRESPONSE']._serialized_end=246
  _globals['_ORDERSERVICE']._serialized_start=248
  _globals['_ORDERSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
