# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n\x0f\x43ustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"\x8f\x01\n\rCustomerOrder\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x14\n\x0corder_status\x18\x03 \x01(\t\x12\x41\n\x1dorder_delivered_customer_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"<\n\x10\x43ustomerResponse\x12(\n\x10\x63ostumers_orders\x18\x01 \x03(\x0b\x32\x0e.CustomerOrder2F\n\x0cOrderService\x12\x36\n\x0fGetCustomerInfo\x12\x10.CustomerRequest\x1a\x11.CustomerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERREQUEST']._serialized_start=78
  _globals['_CUSTOMERREQUEST']._serialized_end=116
  _globals['_CUSTOMERORDER']._serialized_start=119
  _globals['_CUSTOMERORDER']._serialized_end=262
  _globals['_CUSTOMERRESPONSE']._serialized_start=264
  _globals['_CUSTOMERRESPONSE']._serialized_end=324
  _globals['_ORDERSERVICE']._serialized_start=326
  _globals['_ORDERSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
